spring:
  application:
    name: member-client
  boot:
    admin:
      client:
        url: http://localhost:8769
server:
  port: 8766

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS